### PR TITLE
fix(#237): Ensure types definitions presence in published packages

### PR DESCRIPTION
**Pull request by rda-wimi**
Fix issue #237  with types folders missing in published packages.

### CODE REVIEW

**Comment by JiLiZART** [comment]
@rda-wimi Excellent work!

**Comment by rda-wimi** [comment]
Thanks Mate. 
I just tested it and, although it's ok for most of the packages, it is not for some (react, vue2 and vue3).

To test my changes in the PR I did `pnpm run types` then `pnpm run build` command and then, to simulate the publishing, a "pack" command in each packages.

Seems like the build one does generate a types folder for all but those three packages. This is a separate issue IMHO (maybe something with nx config ? I'm not an expert with that)

**Comment by JiLiZART** [comment]
@rda-wimi Can you please provide configuration where u check that typings is right?

**Comment by rda-wimi** [comment]
> @rda-wimi Can you please provide configuration where u check that typings is right imported?

Yep. Here is a codesandbox demo (Vite with react + typescript template) with a sample. 
https://codesandbox.io/p/devbox/test-type-error-bbob-pg4lpk
```TSX
// ./src/App.tsx
import BBCode from "@bbob/react";
import presetReact from "@bbob/preset-react";

const plugins = [presetReact()];

function App() {
  return <BBCode plugins={plugins}>[b]bold text[/b]</BBCode>;
}

export default App;

```
The declarations are found for @bbob/preset-react but not @bbob/react (and the type folder is, indeed, missing for the react one but not for the react-preset one)

And the same thing happen in a local env (with create-react-app and vite, same code as the linked one before).

**Pull request merged**
