### PR TITLE
Some specific url tests

### PR DESCRIPTION
**Pull request by arkhamvm**
Tests for current bugs

### CODE REVIEW

**Comment by JiLiZART** [comment]
Hi, Yes this is an issue for the parser to detect situations like this `url = https://github.com/JiLiZART/bbob/search?q = any&unscoped_q = any`.
But it's can be avoided by using quotes like this `[url="https://github.com/JiLiZART/bbob/search?q=any&unscoped_q=any"]GET[/url]`

Anyway, I have ideas how to fix this :)

**Comment by arkhamvm** [comment]
> Hi, Yes this is an issue for the parser to detect situations like this `url = https://github.com/JiLiZART/bbob/search?q = any&unscoped_q = any`.
> But it's can be avoided by using quotes like this `[url="https://github.com/JiLiZART/bbob/search?q=any&unscoped_q=any"]GET[/url]`
> 
> Anyway, I have ideas how to fix this :)

Can you fix it asap, please? Or share your ideas, maybe i try to implement it.

**Comment by JiLiZART** [comment]
The main idea is that parser doesn't need to wait for char '=', only whitespace char. You can see it there https://github.com/JiLiZART/bbob/blob/master/packages/bbob-parser/src/lexer.js#L118 (this part of code need to be rewritten)

**Comment by JiLiZART** [comment]
Good news! I rewrite lexer, now it passes this url tests

**Comment by JiLiZART** [comment]
Fixed in https://github.com/JiLiZART/bbob/pull/79

**Pull request closed without merging**
