### PR TITLE
Allow to pass dynamic data in options for render

### PR DESCRIPTION
**Pull request by arkhamvm**
```ts
const data = {
  copyrightText: 'my awesome site',
};
const processor = (BbobCore(myPreset)).process(content, {render, data});
```

```ts
const myPreset = BbobPresetHTML5.extend((tags: any) => ({
	...tags,
        copyright: (node: any, { render, data }) => ({
          tag: 'b',
          content: '© ' + data.copyrightText,
        }),
}));
```

### CODE REVIEW

**Comment by arkhamvm** [comment]
@JiLiZART Hi, can you review it please? :)

**Comment by JiLiZART** [comment]
Nice feature! Thanks!

**Comment by JiLiZART** [comment]
I fill new release soon!

**Comment by arkhamvm** [comment]
> I fill new release soon!

Can you release it please?)

**Comment by JiLiZART** [comment]
https://github.com/JiLiZART/bbob/releases/tag/v2.5.5 done

**Pull request merged**
